# ***Text Classification Using TensorFlow and TensorFlow Hub***

# **Abstract**
This document outlines the development of a text classification model using TensorFlow and TensorFlow Hub. The model is trained on the AG News Subset dataset, a collection of news articles categorized into four classes. The objective is to demonstrate the process of building, training, and evaluating a text classification model, utilizing a pre-trained text embedding for improved performance and efficiency.

# **Objective**
The primary objective of this project is to create an efficient and accurate text classification model using TensorFlow and TensorFlow Hub. The model aims to classify news articles into four predefined categories: World, Sports, Business, and Sci/Tech. By leveraging pre-trained embeddings, the project seeks to enhance model performance while simplifying the development process.

# **Introduction**
Text classification is a fundamental task in natural language processing (NLP) with applications in sentiment analysis, spam detection, and topic categorization. Pre-trained embeddings, like those available from TensorFlow Hub, provide a way to incorporate contextual information into models, improving their ability to understand and classify text. This project demonstrates how to use these embeddings in a TensorFlow model to classify news articles from the AG News Subset dataset.

# **Methodology**
1. **Data Loading:** Use TensorFlow Datasets to load the AG News Subset dataset, splitting it into training and test sets.
2. **Data Exploration:** Inspect a batch of the dataset to understand its structure and contents.
3. **Embedding Layer:** Utilize a pre-trained embedding layer from TensorFlow Hub to convert text into dense vectors.
4.** Model Construction:** Build a sequential neural network model with an embedding layer, a dense layer with ReLU activation, and an output layer with softmax activation.
5. **Model Compilation:** Compile the model using the Adam optimizer, sparse categorical cross-entropy loss function, and accuracy as a metric.
6. **Training:** Train the model on the training data and validate it on the test data.
7. **Evaluation:** Evaluate the model's performance on the test data and analyze the results.



# ***Code***

In [5]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

In [6]:
train_data, validation_data, test_data = tfds.load(name = "imdb_reviews",
                                                   split=('test[:60%]','test[60%:]','test'),
                                                   as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.B5PV49_1.0.0/imdb_reviews-train.tfrecor…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.B5PV49_1.0.0/imdb_reviews-test.tfrecord…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.B5PV49_1.0.0/imdb_reviews-unsupervised.…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [7]:
train_data

<_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [8]:
train_example_batch, train_labels_batch = next(iter(train_data.batch(10)))

In [9]:
train_example_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"There are films that make careers. For George Romero, it was NIGHT OF THE LIVING DEAD; for Kevin Smith, CLERKS; for Robert Rodriguez, EL MARIACHI. Add to that list Onur Tukel's absolutely amazing DING-A-LING-LESS. Flawless film-making, and as assured and as professional as any of the aforementioned movies. I haven't laughed this hard since I saw THE FULL MONTY. (And, even then, I don't think I laughed quite this hard... So to speak.) Tukel's talent is considerable: DING-A-LING-LESS is so chock full of double entendres that one would have to sit down with a copy of this script and do a line-by-line examination of it to fully appreciate the, uh, breadth and width of it. Every shot is beautifully composed (a clear sign of a sure-handed director), and the performances all around are solid (there's none of the over-the-top scenery chewing one might've expected from a film like this). DING-A-LING-LESS is a film whose time has come.",
   

In [10]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1])>

In [11]:
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape = [], dtype = tf.string, trainable = True)

In [12]:
hub_layer(train_example_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.6288042 , -3.41968   ,  2.3538964 , -1.090299  , -4.526663  ,
        -1.3629551 , -1.8922118 ,  0.3842551 ,  2.905169  , -1.6660526 ,
        -2.1116872 ,  0.79313445, -0.38395414, -0.18156521, -2.6187801 ,
         1.2323933 ,  3.3589573 , -0.9936741 , -2.5625691 , -1.4315554 ],
       [ 2.9872591 , -3.274036  ,  5.5512915 , -1.963732  , -2.9086375 ,
        -3.696365  , -1.5308393 ,  1.0595036 ,  4.598071  , -2.7001915 ,
         0.02290693, -0.5865327 , -2.705091  ,  0.35615894, -4.9680815 ,
         2.2500696 ,  5.1109447 , -3.8261738 , -4.399767  , -2.1615112 ],
       [ 1.7833786 , -5.4642234 ,  5.293636  , -3.2864733 , -4.809672  ,
        -3.110124  , -3.2357113 ,  0.3689915 ,  4.2027273 , -2.595456  ,
        -4.785997  ,  0.94734   , -0.23603635, -0.564825  , -4.7517996 ,
         2.7173336 ,  4.587659  , -2.0358074 , -4.636639  , -1.502173  ]],
      dtype=float32)>

In [13]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 20)                400020    
                                                                 
 dense (Dense)               (None, 16)                336       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 400373 (1.53 MB)
Trainable params: 400373 (1.53 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.compile(optimizer='adam',loss =tf.keras.losses.BinaryCrossentropy(from_logits=True), metrics=['accuracy'])

In [16]:
history = model.fit(train_data.shuffle(10000).batch(100), epochs = 25,
                    validation_data = validation_data.batch(100), verbose = 1)

Epoch 1/25
150/150 [==============================] - 6s 33ms/step - loss: 0.6241 - accuracy: 0.6269 - val_loss: 0.5308 - val_accuracy: 0.6915
Epoch 2/25
150/150 [==============================] - 3s 21ms/step - loss: 0.4671 - accuracy: 0.7685 - val_loss: 0.4296 - val_accuracy: 0.8083
Epoch 3/25
150/150 [==============================] - 3s 21ms/step - loss: 0.3678 - accuracy: 0.8328 - val_loss: 0.3646 - val_accuracy: 0.8211
Epoch 4/25
150/150 [==============================] - 5s 30ms/step - loss: 0.2953 - accuracy: 0.8752 - val_loss: 0.3261 - val_accuracy: 0.8465
Epoch 5/25
150/150 [==============================] - 3s 21ms/step - loss: 0.2460 - accuracy: 0.8970 - val_loss: 0.3048 - val_accuracy: 0.8658
Epoch 6/25
150/150 [==============================] - 3s 21ms/step - loss: 0.2054 - accuracy: 0.9176 - val_loss: 0.2914 - val_accuracy: 0.8675
Epoch 7/25
150/150 [==============================] - 4s 24ms/step - loss: 0.1755 - accuracy: 0.9325 - val_loss: 0.2966 - val_accuracy: 0.8607

In [17]:
results = model.evaluate(test_data.batch(100), verbose=2)
for name, value in zip(model.metrics_names, results):
  print("%s: %3f" % (name, value))

250/250 - 3s - loss: 0.2265 - accuracy: 0.9464 - 3s/epoch - 12ms/step
loss: 0.226532
accuracy: 0.946360


# **Conclusion**
This project successfully demonstrates the creation of a text classification model using TensorFlow and TensorFlow Hub. By leveraging pre-trained embeddings, the model effectively classifies news articles into four categories with a high degree of accuracy. This approach simplifies the process of building robust NLP models and showcases the potential of transfer learning in text classification tasks. Future work could involve experimenting with different pre-trained embeddings and model architectures to further enhance performance.